---
- name: Deploy the vLLM pod and benchmark whisper while gathering dcgm metrics and render some usage plots
  hosts: localhost
  gather_facts: no
  tasks:
  - import_role:
      name: psap.bench.smi_gather
    vars:
      collect_metrics_enabled: true
      stop_metrics_enabled: false

  - import_role:
      name: psap.bench.whisper

  - import_role:
      name: psap.bench.smi_gather
    vars:
      collect_metrics_enabled: false
      stop_metrics_enabled: true

  - import_role:
      name: psap.bench.plotter
