---
- name: "main: Include collect metrics tasks"
  include_tasks: collect_metrics.yml
  when: collect_metrics_enabled | default(false)

- name: "main: Include stop metrics tasks"
  include_tasks: stop_metrics.yml
  when: stop_metrics_enabled | default(false)
